version: '3'

services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
          - rabbitmq_go_net

  goapp: 
    build:
      context: .
    ports:
      - "8555:8080"
    networks:
      - rabbitmq_go_net
    container_name: 'go-rabbit-app'
    depends_on:
      - rabbitmq
    restart: always
    entrypoint: dockerize -wait tcp://rabbitmq:5672 -timeout 1m ./main


networks:
  rabbitmq_go_net:
    driver: bridge
