version: '3'

services:
  goapp: 
    image: golang:1.12.5-alpine3.9
    container_name: goapp
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8555:8080"
    command: go mod tidy
    command: go run cmd/main.go
    tty: true

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
          - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
          - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
